### ISSUE TITLE
Uncaught ArgumentCountError: pi() expects exactly 0 arguments, 1 given

### ISSUE THREAD

**Issue by johanflorez** [hyperized/benchmark#27]
hi
I'm receiving this error: PHP Fatal error:  Uncaught ArgumentCountError: pi() expects exactly 0 arguments, 1 given

script output

<pre>== Generic PHP information

PHP version: 8.0.8
Server: Probably CLI
Maximum execution time: 0 seconds

Maximum memory size: 1.00 B (1 bytes)
Maximum upload size: 2.00 MB (2097152 bytes)

Modules loaded:
 Core (8.0.8)
 date (8.0.8)
 libxml (8.0.8)
 openssl (8.0.8)
 pcre (8.0.8)
 zlib (8.0.8)
 filter (8.0.8)
 hash (8.0.8)
 json (8.0.8)
 pcntl (8.0.8)
 Reflection (8.0.8)
 SPL (8.0.8)
 session (8.0.8)
 standard (8.0.8)
 sodium (8.0.8)
 mysqlnd (mysqlnd 8.0.8)
 PDO (8.0.8)
 calendar (8.0.8)
 ctype (8.0.8)
 exif (8.0.8)
 FFI (8.0.8)
 fileinfo (8.0.8)
 ftp (8.0.8)
 gettext (8.0.8)
 iconv (8.0.8)
 imagick (3.4.4)
 mysqli (8.0.8)
 pdo_mysql (8.0.8)
 Phar (8.0.8)
 posix (8.0.8)
 readline (8.0.8)
 shmop (8.0.8)
 sockets (8.0.8)
 sysvmsg (8.0.8)
 sysvsem (8.0.8)
 sysvshm (8.0.8)
 tokenizer (8.0.8)
 Zend OPcache (8.0.8)
 
== Disk performance information
Results sorted by file size (in bytes) in milliseconds (less is better), for a total of 100 cycles:
+---------------------+--------------------+--------------------+--------------------+--------------------+---------------------+---------------------+---------------------+
|         512         |        1024        |        2048        |        4096        |        8192        |        16384        |        32678        |        65536        |
+---------------------+--------------------+--------------------+--------------------+--------------------+---------------------+---------------------+---------------------+
| 0.0045874118804932  | 0.0044596195220947 | 0.0051333904266357 | 0.007610559463501  | 0.005415678024292  | 0.0058000087738037  | 0.0067505836486816  | 0.0086522102355957  |
+---------------------+--------------------+--------------------+--------------------+--------------------+---------------------+---------------------+---------------------+
 
PHP Fatal error:  Uncaught ArgumentCountError: pi() expects exactly 0 arguments, 1 given in /var/www/home1.local/benchmark/src/Modules/CPU.php:147
Stack trace:
#0 /var/www/home1.local/benchmark/src/Modules/CPU.php(147): pi()
#1 /var/www/home1.local/benchmark/src/Modules/CPU.php(132): Hyperized\Benchmark\Modules\CPU->math()
#2 /var/www/home1.local/benchmark/src/Modules/CPU.php(111): Hyperized\Benchmark\Modules\CPU->run()
#3 /var/www/home1.local/benchmark/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(143): Hyperized\Benchmark\Modules\CPU->__construct()
#4 /var/www/home1.local/benchmark/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(71): DI\Definition\Resolver\ObjectCreator->createInstance()
#5 /var/www/home1.local/benchmark/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(71): DI\Definition\Resolver\ObjectCreator->resolve()
#6 /var/www/home1.local/benchmark/vendor/php-di/php-di/src/Container.php(390): DI\Definition\Resolver\ResolverDispatcher->resolve()
#7 /var/www/home1.local/benchmark/vendor/php-di/php-di/src/Container.php(139): DI\Container->resolveDefinition()
#8 /var/www/home1.local/benchmark/vendor/php-di/php-di/src/Definition/Reference.php(53): DI\Container->get()
#9 /var/www/home1.local/benchmark/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(66): DI\Definition\Reference->resolve()
#10 /var/www/home1.local/benchmark/vendor/php-di/php-di/src/Definition/Resolver/ParameterResolver.php(78): DI\Definition\Resolver\ResolverDispatcher->resolve()
#11 /var/www/home1.local/benchmark/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(138): DI\Definition\Resolver\ParameterResolver->resolveParameters()
#12 /var/www/home1.local/benchmark/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(71): DI\Definition\Resolver\ObjectCreator->createInstance()
#13 /var/www/home1.local/benchmark/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(71): DI\Definition\Resolver\ObjectCreator->resolve()
#14 /var/www/home1.local/benchmark/vendor/php-di/php-di/src/Container.php(390): DI\Definition\Resolver\ResolverDispatcher->resolve()
#15 /var/www/home1.local/benchmark/vendor/php-di/php-di/src/Container.php(139): DI\Container->resolveDefinition()
#16 /var/www/home1.local/benchmark/benchmark.php(15): DI\Container->get()
#17 {main}
  thrown in /var/www/home1.local/benchmark/src/Modules/CPU.php on line 147

config.yml

---
benchmark:
  php:
    enabled: true
  disk:
    enabled: true
    cycles: 100
  cpu:
    enabled: true
    math:
      count: 99999
    strings:
      count: 99999
    loops:
      count: 99999
    ifElse:
      count: 99999
  mysql:
    enabled: false
    count: 1000000
    hostname: localhost
    port: 3306
    username: root
    password: 
    database: wp1

**Comment by hyperized** [comment]
Fixed in v1.0.0. The CPU module now separates math functions by their call signatures — `pi()` is in its own group and called without arguments.
